# Generated by Django 4.2.3 on 2024-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
