# Generated by Django 4.2.3 on 2024-03-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0002_messageform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageForm',
        ),
    ]
