# Generated by Django 4.2.3 on 2024-03-27 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0004_dog_delete_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='name',
        ),
    ]
