# Generated by Django 4.2.3 on 2024-03-27 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0006_alter_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
