# Generated by Django 4.2.3 on 2024-03-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0007_alter_dog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
