# Generated by Django 4.2.3 on 2024-03-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0009_remove_dog_image_remove_dog_name_dog_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dog',
            new_name='Textmod',
        ),
    ]
